name=EasyConnectevity
version=1.0.0
author=Souhardo Das
maintainer=Souhardo Das <souhardodasdps1@gmail.com>
sentence=Plug-and-play sensor, pin, and cloud helper library for ESP and Arduino boards.
paragraph=EasyConnectevity simplifies sensor handling, GPIO control, and cloud communication for ESP8266, ESP32, and Arduino boards. Designed for fast prototyping and production-ready IoT projects.
category=Communication
url=https://github.com/souhardodasdps1-commits/EasyConnectevity
architectures=*
license=MIT
