name=EasyConnectevity
version=1.0.0
author=Souhardo Das
maintainer=souhardodasdps1@gmail.com
sentence=Plug-and-play sensor, pin, and cloud library for ESP and Arduino boards.
paragraph=EasyConnectevity works with ESP32, ESP8266, Wemos, NodeMCU, and standard Arduino boards. Read sensors, control pins, and send data to cloud services easily.
category=Connectivity
url=https://github.com/SouhardoDas/EasyConnectevity
architectures=*
